

services:
  coursework-db:
    image: mysql:8.0
    restart: always
    container_name: Coursework-db
    environment:
      MYSQL_DATABASE: shop_db
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
